export const proposalConst = {

  // Proposal kind
  kind: {
    PROPOSAL_KIND_ADD_MEMBER: 0,
    PROPOSAL_KIND_DELETE_MEMBER: 1,
    PROPOSAL_KIND_USE_OF_FUNDS: 2,
    PROPOSAL_KIND_COMMUNITY_MANAGEMENT: 3,
    PROPOSAL_KIND_ACTIVITIES: 4,
    PROPOSAL_KIND_ELECTION_COMISSION_PROPOSAL: 5,
    PROPOSAL_KIND_DAO_REWARD: 6,
  },
  status: {
    // Proposal status
    PROPOSAL_STATUS_UNDER_DISCUSSION_ON_GITHUB: 0,
    PROPOSAL_STATUS_VOTING: 1,
    PROPOSAL_STATUS_PENDING: 2,
    PROPOSAL_STATUS_RUNNING: 3,
    PROPOSAL_STATUS_REJECTED: 4,
    PROPOSAL_STATUS_FINISHED_VOTING: 5,
    PROPOSAL_STATUS_FINISHED: 6,
  }
}

export const tokenConst = {
  // token kind
  TOKEN_KIND_ERC20: 0,
  TOKEN_KIND_ERC721: 1,
  ADDRESS_ZERO: "0x0000000000000000000000000000000000000000",
}
