export const proposalManagerContractAddress = process.env.NEXT_PUBLIC_PROPOSAL_MANAGER_CONTRACT_ADDRESS
export const masterDAOContractAddress = process.env.NEXT_PUBLIC_MASTERDAO_CONTRACT_ADDRESS
export const memberManagerContractAddress = process.env.NEXT_PUBLIC_MEMBER_MANAGER_CONTRACT_ADDRESS
